### ISSUE TITLE
Some typos in README

### ISSUE THREAD

**Issue by b04505009** [qa276390/Encrypted_Traffic_Classification#1]
`cd prerpo &&　sh multi_gen.sh ../data/JSON Table.csv 0 && python3 toTrain.py Table.csv`
should be
`cd prepro && sh multi_gen.sh ../data/JSON Table.csv 0 && python3 toTrain.py Table.csv`

**Comment by WANGxue708** [comment]
Excuse me, when I typed sh multi_gen.sh. / data / JSON Table. CSV 0 in the shell, the following error occurred. 
##
wangxue@D003:/home/Encrypted_Traffic_Classification/prepro$ sh multi_gen.sh /home/Encrypted_Traffic_Classification/data/JSON Table_2_25.csv 0
##
this is the error:
multi_gen.sh: 4: multi_gen.sh: parallel: not found

I don't know what's going on. I'm here to consult you.

**Comment by qa276390** [comment]
Hi, please make sure you have installed [GNU parallel](https://www.gnu.org/software/parallel/) on your device.

**Comment by qa276390** [comment]
> Excuse me, when I typed sh multi_gen.sh. / data / JSON Table. CSV 0 in the shell, the following error occurred.
> 
> wangxue@D003:/home/Encrypted_Traffic_Classification/prepro$ sh multi_gen.sh /home/Encrypted_Traffic_Classification/data/JSON Table_2_25.csv 0
> 
> this is the error:
> multi_gen.sh: 4: multi_gen.sh: parallel: not found
> 
> I don't know what's going on. I'm here to consult you.

Hi, please make sure you have installed [GNU parallel](https://www.gnu.org/software/parallel/) on your device.

**Comment by WANGxue708** [comment]
Hello, when I ran to cd. / main & sh TRAIN. sh DNN, the following error occurred:

Traceback (most recent call last):
  File "train.py", line 556, in <module>
    DNN(opts)
  File "train.py", line 256, in DNN
    X_train = np.load(opts.source_data_folder+'/X_train.npy')
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/liuxueyan/workspace/MtProject/data_pkt30/X_train.npy'

In addition, I would like to ask if this code needs to install the tensorflow version of GPU?

**Comment by qa276390** [comment]
> Hello, when I ran to cd. / main & sh TRAIN. sh DNN, the following error occurred:
> 
> Traceback (most recent call last):
> File "train.py", line 556, in 
> DNN(opts)
> File "train.py", line 256, in DNN
> X_train = np.load(opts.source_data_folder+'/X_train.npy')
> File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 415, in load
> fid = open(os_fspath(file), "rb")
> FileNotFoundError: [Errno 2] No such file or directory: '/home/liuxueyan/workspace/MtProject/data_pkt30/X_train.npy'

Please try again, I have fixed that.


> 
> In addition, I would like to ask if this code needs to install the tensorflow version of GPU?

tf of GPU version is optional but highly recommended.

**Comment by nankaiding** [comment]
Excuse me, my datasets is from VPN-nonVPN dataset (ISCXVPN2016),  I run to " sh pcap_to_json.sh tmpJSON JSON 100 ",the resulting json files named with vpn are 0 byte in size, and why the prefix is "add" in your JSON file with "vpn" , thanks @qa276390

**Comment by qa276390** [comment]
> Excuse me, my datasets is from VPN-nonVPN dataset (ISCXVPN2016), I run to " sh pcap_to_json.sh tmpJSON JSON 100 ",the resulting json files named with vpn are 0 byte in size, and why the prefix is "add" in your JSON file with "vpn" , thanks @qa276390

Hi @nankaiding , sorry for the late reply. The VPN file in ` VPN-nonVPN dataset (ISCXVPN2016)` are kind of losing some information.  Joy  doesn’t known the **Netmask** of the traffic.

All you need to do is using the [tcprewrite](https://linux.die.net/man/1/tcprewrite) to modify it.
for example, 
```shell
tcprewrite --file=[FILE] --dlt=enet --outfile=[OUTPUT] --enet-dmac=00:55:22:AF:C6:37 -enet-smac=00:44:66:FC:29:AF
```
