### ISSUE TITLE
相关Paper

### ISSUE THREAD

**Issue by JianhaoChung** [qa276390/Encrypted_Traffic_Classification#3]
您好，请问该项目代码是根据那篇论文进行复现的吗？

**Comment by qa276390** [comment]
No it’s not. We only borrowed the concept and the dataset from the paper mentioned.

**Comment by JianhaoChung** [comment]
Excuse me, is there any loss in data conversion from PACP file to JSON?

**Comment by qa276390** [comment]
There are some parameters to set, as we mentioned in Data Preprocessing. 
To get detail options please refer to [joy](https://github.com/cisco/joy).
